config/routes.rb
Rails.application.routes.draw do
  get 'diaries/new'
  post 'diaries/create'
  post 'diaries/update'
  get 'diaries/edit'
  post 'diaries/destroy'
  get 'diaries/index'
  get 'diaries/show'

  get 'entries/new'
  post 'entries/create'
  post 'entries/update'
  get 'entries/edit'
  post 'entries/destroy'
  get 'entries/index'
  get 'entries/show'

  devise_for :users
  root 'main#index'
  get 'main/index'
  resources :diaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  has_many :users
  has_many :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :diary
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  has_one :diary
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      current_user.update_attribute('diary_id', @diary.id)
      flash[:success] = "Diary created!"
      redirect_to root_url
    else
      render 'main/index'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @diaries = Diary.all
  end

  def show
    if params[:id].to_i == current_user.diary_id
      @diary = Diary.find(params[:id])
    else
      flash[:warning] = "nonononono ACCESS"
      redirect_to root_url
    end
  end

  private

  def diary_params
    params.require(:diary).permit(:name)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/diaries/edit.html.erb
<h1>Diaries#edit</h1>
<p>Find me in app/views/diaries/edit.html.erb</p>

app/views/diaries/index.html.erb
<h1>All diaries</h1>
<ul class="diaries">
  <% @diaries.each do |diary| %>
    <h3><%= link_to diary.name, diary %></h3>
  <% end %>
</ul>

app/views/diaries/new.html.erb
<%= form_for @diary, url: {action: "create"}, html: {class: "diary_form"} do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/diaries/show.html.erb
<h1>Diary: <%= @diary.name %></h1>
<p>Here will be your diary! </p>

app/views/diaries/update.html.erb
<h1>Diaries#update</h1>
<p>Find me in app/views/diaries/update.html.erb</p>

app/views/entries/create.html.erb
<h1>Entries#create</h1>
<p>Find me in app/views/entries/create.html.erb</p>

app/views/entries/destroy.html.erb
<h1>Entries#destroy</h1>
<p>Find me in app/views/entries/destroy.html.erb</p>

app/views/entries/edit.html.erb
<h1>Entries#edit</h1>
<p>Find me in app/views/entries/edit.html.erb</p>

app/views/entries/index.html.erb
<h1>Entries#index</h1>
<p>Find me in app/views/entries/index.html.erb</p>

app/views/entries/new.html.erb
<h1>Entries#new</h1>
<p>Find me in app/views/entries/new.html.erb</p>

app/views/entries/show.html.erb
<h1>Entries#show</h1>
<p>Find me in app/views/entries/show.html.erb</p>

app/views/entries/update.html.erb
<h1>Entries#update</h1>
<p>Find me in app/views/entries/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <title>CouplesDiary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<nav>
  <% if  user_signed_in? %>
    <% if current_user.diary_id.present? %>
      <li><%= link_to 'Your diary', diary_path(current_user.diary_id) %></li>
    <% else %>
      <li><%= link_to 'Create a diary', new_diary_path %></li>
    <% end %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  <% else %>
    <li><%= link_to 'Login', user_session_path  %></li>
    <li><%= link_to 'Register', new_user_registration_path %></li>
  <% end %>
</nav>
<h1>This will be couples diary app!</h1>
<p>Find me for better styling in app/views/main/index.html.erb</p>